AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 200

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'
    
Metrics/BlockLength:
  Max: 110
  
Metrics/MethodLength:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10
